### ISSUE TITLE
ipec.conf include section not work

### ISSUE THREAD

**Issue by AShabana** [leforestier/ipsecparse#1]
Do this works with include dir ?

**Comment by leforestier** [comment]
An 

```
include ipsec.*.conf
```

entry in the configuration file

corresponds to an `('include', 'ipsec.*.conf')` key in the IpsecConf instance.

You could iterate over the includes like this:

```
>>> for instruction, value in conf.keys():
...     if instruction == 'include':
...         print(value)
... 

/etc/ipsec.d/*.conf
/etc/ipsec.d/*.secrets
```

The `loads` function doesn't try to read or parse the included files if that's what you're asking.

**Comment by AShabana** [comment]
yes , this is the point , it is not try to read or parse the include files .as my setup rely on include 
anyway many thanks for your work.

**Comment by povilasb** [comment]
Seems like this issue can be closed? :)
