### ISSUE TITLE
Can't seem to get it to parse /etc/ipsec.conf

### ISSUE THREAD

**Issue by benileo** [leforestier/ipsecparse#2]
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import ipsecparse
> > > conf = ipsecparse.loads(open("/etc/ipsec.conf", "rw") )
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/ipsecparse/parser.py", line 66, in parse
> > >     lexer = self._lexer.lexer
> > >   File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
> > >     return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
> > >   File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1012, in parseopt_notrack
> > >     lexer.input(input)
> > >   File "/usr/local/lib/python2.7/dist-packages/ply/lex.py", line 250, in input
> > >     c = s[:1]
> > > TypeError: 'file' object has no attribute '__getitem__'

**Comment by leforestier** [comment]
`loads` loads the config from a string, not a file object. You need to do:

``` python
import ipsecparse
conf = ipsecparse.loads(open("/etc/ipsec.conf").read())
```

**Comment by benileo** [comment]
Thank you.
